export const DOGS_DATA_REQUEST = 'DOGS_DATA_REQUEST'
export const DOGS_DATA_SUCCESS = 'DOGS_DATA_SUCCESS'
export const DOGS_DATA_FAIL = 'DOGS_DATA_FAIL'

export const SET_DOG_AS_FAVOURITE = 'SET_DOG_AS_FAVOURITE'
export const REMOVE_DOG_FROM_FAVOURITE = 'REMOVE_DOG_FROM_FAVOURITE'
